import { supabase } from '@/lib/supabase';

import { z } from 'zod';

const ClientSchema = z.object({
  name: z.string().min(1, 'El nombre es obligatorio'),
  email: z.string().email('Email inválido').optional().or(z.literal('')),
  phone: z.string().optional().or(z.literal('')),
  company: z.string().optional().or(z.literal('')),
  notes: z.string().optional().or(z.literal('')),
  location: z.string().optional().or(z.literal('')),
  assigned_salesperson_id: z
    .string()
    .uuid('ID de vendedor inválido')
    .optional()
    .or(z.literal('')),
});

type ClientData = z.infer<typeof ClientSchema>;

interface Product {
  id: string;
  name: string;
  price: number;
  keywords: string[];
}

interface Item {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
}

async function autoGenerateDraftProforma(
  clientId: string,
  notes: string,
  salespersonId: string
): Promise<{ success: boolean; error?: string }> {
  if (!notes || notes.trim() === '')
    return { success: false, error: 'Notes are required' };

  // Usar Service Role Key para automatizaciones backend y saltarse el RLS

  try {
    // 2. Crear proyecto en borrador usando las 'notes' como 'title' (asunto de trámite)
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .insert({
        title: notes.substring(0, 50) + (notes.length > 50 ? '...' : ''), // Asunto corto
        description: notes, // Asunto completo
        client_id: clientId,
        assigned_salesperson_id: salespersonId,
        status: 'PENDING',
        expected_revenue: 0,
      })
      .select('id')
      .single();

    if (projectError) {
      console.error('Error creating project in autoGenerate:', projectError);
      return { success: false, error: projectError.message };
    }

    if (project) {
      // 3. Crear proforma en borrador sin items pero con la info base
      const { error: proformaError } = await supabase.from('proformas').insert({
        project_id: project.id,
        items: [],
        total: 0,
        status: 'PENDING',
      });
      if (proformaError) {
        console.error(
          'Error creating proforma in autoGenerate:',
          proformaError
        );
        return { success: false, error: proformaError.message };
      }
    }
    return { success: true };
  } catch (err: unknown) {
    console.error('Critical error in autoGenerateDraftProforma:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Error desconocido',
    };
  }
}

export async function createClientRecord(rawData: unknown) {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error('No autorizado');

  const { data: is_admin } = await supabase.rpc('is_admin');
  if (!is_admin) {
    throw new Error('Solo los administradores pueden registrar clientes.');
  }

  // Validar con Zod
  const validationResult = ClientSchema.safeParse(rawData);
  if (!validationResult.success) {
    throw new Error(`Datos inválidos: ${validationResult.error.message}`);
  }
  const data = validationResult.data;

  // Limpiar empty strings a nulls o omitirlos
  const cleanData = Object.fromEntries(
    Object.entries(data).filter(([_, v]) => v !== '')
  );

  const { data: newClient, error } = await supabase
    .from('clients')
    .insert(cleanData)
    .select('id')
    .single();

  if (error) {
    throw new Error(`Error creando cliente: ${error.message}`);
  }

  if (data.assigned_salesperson_id && newClient) {
    // Generar proforma en borrador automáticamente
    if (data.notes) {
      await autoGenerateDraftProforma(
        newClient.id,
        data.notes,
        data.assigned_salesperson_id
      );
    }
    const { notifyUser } = await import('./notifications');
    await notifyUser(
      data.assigned_salesperson_id,
      `Te han asignado un nuevo cliente: ${data.name}`,
      'info'
    );
  }

  return { success: true };
}

export async function updateClientRecord(clientId: string, rawData: unknown) {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error('No autorizado');

  const { data: is_admin } = await supabase.rpc('is_admin');
  if (!is_admin) {
    throw new Error('Solo los administradores pueden editar clientes.');
  }

  // Validar con Zod
  const validationResult = ClientSchema.safeParse(rawData);
  if (!validationResult.success) {
    throw new Error(`Datos inválidos: ${validationResult.error.message}`);
  }
  const data = validationResult.data;

  // Limpiar empty strings a nulls o omitirlos
  const cleanData = Object.fromEntries(
    Object.entries(data).filter(([_, v]) => v !== '')
  );

  const { error } = await supabase
    .from('clients')
    .update(cleanData)
    .eq('id', clientId);

  if (error) {
    throw new Error(`Error actualizando cliente: ${error.message}`);
  }

  if (data.assigned_salesperson_id) {
    // Verificamos si ya tiene proyectos asignados para no crear duplicados cada vez que se edita
    const { count } = await supabase
      .from('projects')
      .select('*', { count: 'exact', head: true })
      .eq('client_id', clientId);
    if (count === 0 && data.notes) {
      await autoGenerateDraftProforma(
        clientId,
        data.notes,
        data.assigned_salesperson_id
      );
    }
    const { notifyUser } = await import('./notifications');
    await notifyUser(
      data.assigned_salesperson_id,
      `Te han asignado un nuevo cliente: ${data.name}`,
      'cliente'
    );
  }

  return { success: true };
}

export async function deleteClientRecord(clientId: string) {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error('No autorizado');

  const { data: is_admin } = await supabase.rpc('is_admin');
  if (!is_admin) {
    throw new Error('Solo los administradores pueden eliminar clientes.');
  }

  const { error } = await supabase.from('clients').delete().eq('id', clientId);

  if (error) {
    throw new Error(`Error eliminando cliente: ${error.message}`);
  }

  return { success: true };
}

export async function createNewDraftFromHistory(
  clientId: string,
  notes: string,
  salespersonId: string
) {
  if (!notes || !notes.trim()) {
    throw new Error('La descripción es obligatoria para generar un borrador.');
  }

  const { success, error } = await autoGenerateDraftProforma(
    clientId,
    notes,
    salespersonId
  );

  if (!success) {
    throw new Error(error || 'No se pudo generar el borrador automático.');
  }

  if (salespersonId) {
    const { notifyUser } = await import('./notifications');
    await notifyUser(
      salespersonId,
      'Se ha generado un nuevo borrador automático para un cliente asignado a ti.',
      'proforma'
    );
  }

  return { success: true };
}
